# Generated by Django 4.2.7 on 2023-12-21 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Минимум: 1 единица')], verbose_name='Количество ингредиента в рецепте'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, help_text='Загрузите изображение блюда', null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
